Current structure of the recieved order object over webhooks
Knawat/types pull request #1
Opened 2020-12-27 10:36 UTC by cactusaurelius

## :memo: Description

The address in orders received over webhooks is named dilevery_address

### :gem: Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### :scroll: Example code
```js
      order.shipping = order.shipping || order.deliveryAddress;

``` 

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2020-12-27 15:39 UTC, HazemKhaled requested changes

2020-12-27 15:39 UTC, HazemKhaled commented on src/order.ts
> +  deliveryAddress?: Address;
this order object fro sales order, you need to create new PurchaseOrder type

2020-12-28 06:48 UTC, HazemKhaled requested changes

2020-12-28 06:48 UTC, HazemKhaled commented on src/purchaseorder.ts
> +export interface item {
The naming convention should be camel case
use `PurchaseOrderItem` instead

make sure all fields are included https://docs.knawat.io/#tag/Orders/paths/~1async~1orders/post

2020-12-28 06:48 UTC, HazemKhaled commented on src/purchaseorder.ts
> +  deliveryAddress: Address;
Instead, add issue to @neer14 to fix deliveryAddress and remove it from here

in you app SEA, extend it for now

2020-12-30 10:49 UTC, neer14 commented on src/purchaseorder.ts
> +}
Missing date,referenceNumber, receivedStatus, billedStatus, exchangeRate, isDropShipment, salesorderId, adjustment, adjustmentDescription, subTotalInclusiveOfTax,taxTotal, deliveryOrgAddressId, deliveryCustomerId, createdTime, lastModifiedTime, comments, bills, salesorders, taxes, purchasereceives

2020-12-30 10:49 UTC, neer14 commented on src/purchaseorder.ts
> +  total: number;
missing id,accountId,taxType

2021-01-01 14:28 UTC, HazemKhaled approved these changes

2021-01-01 14:28 UTC, merged