add supplier types
Knawat/types pull request #2
Opened 2020-12-27 10:42 UTC by cactusaurelius

## :memo: Description

Knawat supplier types

- [x] New feature (non-breaking change which adds functionality)

## :checkered_flag: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2020-12-27 15:41 UTC, HazemKhaled requested changes

2020-12-27 15:41 UTC, HazemKhaled commented on src/supplier.ts
> +    id: string;
make sure to have all fields from here https://docs.knawat.io/?url=https://suppliers.knawat.io/openapi/openapi.json#tag/Suppliers/paths/~1suppliers~1{id}/get

2020-12-27 15:41 UTC, HazemKhaled commented on src/supplier.ts
> +  export interface Webhook {
create file for each type, this should be in webhook.ts
```json
{
  "id": "5f3bc66f576f0d3768be3376",
  "topic": "porders.create",
  "supplierId": "ID",
  "url": "https://example.com/webhook",
  "createdAt": "2020-08-18T14:55:42.941+03:00",
  "updatedAt": "2020-08-18T14:55:42.941+03:00"
}
```

2020-12-28 06:46 UTC, HazemKhaled commented
@neer14 once approved request my review please

2020-12-29 06:15 UTC, neer14 commented on src/supplier.ts
> +}
missing jscrapper_urls
last_translation_update should be Date

2020-12-29 06:19 UTC, neer14 commented on src/supplier.ts
> +  apply_to: string[]
I will update appy_to later after pipeline pr is completed

2020-12-29 06:27 UTC, cactusaurelius commented on src/supplier.ts
> +}
Done

2020-12-30 10:36 UTC, merged