[MP-463] Add types used in other projects
Knawat/types pull request #28
Opened 2021-06-01 19:10 UTC by cactusaurelius

## :memo: Description

### :dart: Relevant issues

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Example code
```js

``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## :checkered_flag: Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

2021-06-03 12:00 UTC, HazemKhaled requested changes

2021-06-04 13:57 UTC, HazemKhaled requested changes

2021-06-04 13:57 UTC, HazemKhaled commented on src/invoice.ts
> +  shipping_charge: number;
Why `shippingCharge` and `shipping_charge`?

fix it please

2021-06-04 13:57 UTC, HazemKhaled commented on src/invoice.ts
> +  adjustment: number;
It should be as same as invoice, no need to have 2 types

2021-06-04 13:57 UTC, HazemKhaled commented on src/invoice.ts
> +export interface OmsApplyCreditResponse {
Name should be serviceActionNameParamas or serviceActioNameResponse

ex: invoiceGetParams

2021-06-04 13:57 UTC, HazemKhaled commented on src/payment.ts
> +export interface PaymentInvoiceResponse {
make it serviceActionNameResponse

2021-06-04 13:57 UTC, HazemKhaled commented on src/payment.ts
> +  reference_number?: string;
underscore or camel case?

2021-06-04 13:57 UTC, HazemKhaled commented on src/sales-order/order.ts
> +  shipping_charge: number;
duplicated

2021-06-07 06:38 UTC, cactusaurelius commented on src/payment.ts
> +  reference_number?: string;
response from OMS is camel case then sanitized into snake case
https://github.com/Knawat/mp/blob/9fa9d4b07ad7596fddbda025eb5afb86871fd939/services/invoices.service.ts#L290

2021-07-02 07:11 UTC, closed without merging