SAPP-337-Add types for supplier detail and item external_id
Knawat/types pull request #30
Opened 2021-06-02 08:01 UTC by neer14

## :memo: Description

- Add types to show supplier details
  supplierName: string;
  supplierUrl: string;
  vendorId: string;
  vendorName?: string;
- Add externalId type in item
https://knawat.atlassian.net/browse/SAPP-337

### :gem: Type of change

- [X] New feature (non-breaking change which adds functionality)

## :checkered_flag: Checklist:

- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

2021-06-03 06:39 UTC, HazemKhaled requested changes

2021-06-03 06:39 UTC, HazemKhaled commented on src/purchase-order/order.ts
> +  vendorName?: string;
Why vendor and supplier? please unify it, vendor or supplier

2021-06-03 06:45 UTC, neer14 commented on src/purchase-order/order.ts
> +  vendorName?: string;
@HazemKhaled 
vendor is from zoho
and supplier is from sp

we will need vendorId to get supplier from sp

since we will move to napm zoho-finance,
npm will only send vendor detail, then we will get supplier detail from vendor in sp-purchase-order app

2021-06-04 08:22 UTC, HazemKhaled requested changes

2021-06-04 08:22 UTC, HazemKhaled commented on src/purchase-order/order.ts
> +  vendorName?: string;
This package for public properties, Zoho fields should not be exposed over API nor public types

replace it with supplierId, and should have the SP supplier id, and SP supplier

2021-06-04 08:22 UTC, HazemKhaled commented on src/purchase-order/order.ts
> +  supplierUrl: string;
What do you mean bu `supplierUrl`? is it product source URL? if yes please make it externalUrl instead

2021-06-04 08:35 UTC, neer14 commented on src/purchase-order/order.ts
> +  vendorName?: string;
we don't get supplier id from zoho (supplier id is our knawat field)
we only get vendor id from zoho

2021-06-04 08:36 UTC, neer14 commented on src/purchase-order/order.ts
> +  supplierUrl: string;
ok

2021-07-02 07:09 UTC, HazemKhaled approved these changes

2021-07-02 07:09 UTC, HazemKhaled commented on src/purchase-order/order.ts
> +  supplierUrl: string;
What happen here?

2021-07-02 07:09 UTC, merged