add product sku and id to pOrder items
Knawat/types pull request #52
Opened 2022-03-29 21:07 UTC by AFZidan

## :memo: Description

### :dart: Relevant issues

### :gem: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :scroll: Example code
```js

``` 

## :vertical_traffic_light: How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## :checkered_flag: Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

2022-03-29 21:19 UTC, omer-77 approved these changes

2022-04-04 07:50 UTC, dhavalsoni9989 approved these changes

2022-04-05 07:45 UTC, mmcomp approved these changes

2022-05-23 10:31 UTC, HazemKhaled requested changes

2022-05-23 10:31 UTC, HazemKhaled commented on src/purchase-order/item.ts
> +  productExternalId: string;
it's optional

2022-06-09 11:24 UTC, anouarkacem approved these changes

2022-08-30 00:59 UTC, closed without merging